<a href="https://colab.research.google.com/github/renatofb98/Data_science_projects/blob/main/projeto_varejo_centrooeste.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd

# códigos de UF do IBGE: GO=52, MT=51, MS=50, DF=53
url_pmc_teste = "https://apisidra.ibge.gov.br/values/t/8880/n3/50,51,52,53/v/all/p/last"
resp = requests.get(url_pmc_teste, headers={"User-Agent": "Mozilla/5.0"}, timeout=60)
data = resp.json()

df_pmc_teste = pd.DataFrame(data[1:])
print(df_pmc_teste.columns.tolist())
df_pmc_teste.head(10)

['NC', 'NN', 'MC', 'MN', 'V', 'D1C', 'D1N', 'D2C', 'D2N', 'D3C', 'D3N', 'D4C', 'D4N']

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,3,Unidade da Federação,30,Número-índice,..,50,Mato Grosso do Sul,7169,PMC - Número-índice (2022=100),202606,junho 2026,0,
1,3,Unidade da Federação,30,Número-índice,..,50,Mato Grosso do Sul,7170,PMC - Número-índice com ajuste sazonal (2022=100),202606,junho 2026,0,
2,3,Unidade da Federação,2,%,..,50,Mato Grosso do Sul,11708,"PMC - Variação mês/mês imediatamente anterior,...",202606,junho 2026,0,
3,3,Unidade da Federação,2,%,..,50,Mato Grosso do Sul,11709,PMC - Variação mês/mesmo mês do ano anterior (...,202606,junho 2026,0,
4,3,Unidade da Federação,2,%,..,50,Mato Grosso do Sul,11710,PMC - Variação acumulada no ano (em relação ao...,202606,junho 2026,0,
5,3,Unidade da Federação,2,%,..,50,Mato Grosso do Sul,11711,PMC - Variação acumulada em 12 meses (em relaç...,202606,junho 2026,0,
6,3,Unidade da Federação,30,Número-índice,..,51,Mato Grosso,7169,PMC - Número-índice (2022=100),202606,junho 2026,0,
7,3,Unidade da Federação,30,Número-índice,..,51,Mato Grosso,7170,PMC - Número-índice com ajuste sazonal (2022=100),202606,junho 2026,0,
8,3,Unidade da Federação,2,%,..,51,Mato Grosso,11708,"PMC - Variação mês/mês imediatamente anterior,...",202606,junho 2026,0,
9,3,Unidade da Federação,2,%,..,51,Mato Grosso,11709,PMC - Variação mês/mesmo mês do ano anterior (...,202606,junho 2026,0,

In [ ]:
url_pmc = "https://apisidra.ibge.gov.br/values/t/8880/n3/50,51,52,53/v/7170/p/all"
resp = requests.get(url_pmc, headers={"User-Agent": "Mozilla/5.0"}, timeout=60)
data = resp.json()

df_pmc = pd.DataFrame(data[1:])
df_pmc = df_pmc.rename(columns={"D1C": "codigo_uf", "D1N": "uf", "D2C": "anomes", "V": "indice_volume_sazonal"})
df_pmc["indice_volume_sazonal"] = pd.to_numeric(df_pmc["indice_volume_sazonal"], errors="coerce")
df_pmc["anomes"] = df_pmc["anomes"].astype(int)

# remove os meses ainda não publicados (valor nulo)
df_pmc = df_pmc.dropna(subset=["indice_volume_sazonal"])

print(df_pmc["anomes"].max(), df_pmc["anomes"].min())
print(df_pmc.groupby("uf")["anomes"].count())

nan nan
Series([], Name: anomes, dtype: int64)

In [ ]:
df_pmc_raw = pd.DataFrame(data[1:])
print(df_pmc_raw["V"].head(10).tolist())

['..', '..', '..', '..', '..', '..', '..', '..', '..', '..']

In [ ]:
print(df_pmc_raw[["D1N", "D2N"]].head(10))
print(df_pmc_raw[["D1N", "D2N"]].tail(10))

                  D1N                                                D2N
0  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
1  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
2  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
3  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
4  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
5  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
6  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
7  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
8  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
9  Mato Grosso do Sul  PMC - Número-índice com ajuste sazonal (2022=100)
                   D1N                                                D2N
1262  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1263  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1264  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1265  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1266  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1267  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1268  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1269  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1270  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)
1271  Distrito Federal  PMC - Número-índice com ajuste sazonal (2022=100)

In [ ]:
df_pmc = df_pmc_raw.rename(columns={
    "D1C": "codigo_uf",
    "D1N": "uf",
    "D3C": "anomes",     # período real está aqui, não em D2C
    "V": "indice_volume_sazonal"
})

df_pmc = df_pmc[df_pmc["indice_volume_sazonal"] != ".."].copy()
df_pmc["indice_volume_sazonal"] = pd.to_numeric(df_pmc["indice_volume_sazonal"], errors="coerce")
df_pmc["anomes"] = df_pmc["anomes"].astype(int)

print(df_pmc["anomes"].max(), df_pmc["anomes"].min())
print(df_pmc.groupby("uf")["anomes"].count())

nan nan
Series([], Name: anomes, dtype: int64)

In [ ]:
print(df_pmc_raw.columns.tolist())
df_pmc_raw.iloc[[0, 600, 1271]]  # uma linha do início, meio e fim

['NC', 'NN', 'MC', 'MN', 'V', 'D1C', 'D1N', 'D2C', 'D2N', 'D3C', 'D3N', 'D4C', 'D4N']

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,3,Unidade da Federação,30,Número-índice,..,50,Mato Grosso do Sul,7170,PMC - Número-índice com ajuste sazonal (2022=100),200001,janeiro 2000,0,
600,3,Unidade da Federação,30,Número-índice,..,51,Mato Grosso,7170,PMC - Número-índice com ajuste sazonal (2022=100),202307,julho 2023,0,
1271,3,Unidade da Federação,30,Número-índice,..,53,Distrito Federal,7170,PMC - Número-índice com ajuste sazonal (2022=100),202606,junho 2026,0,

In [ ]:
df_pmc_raw["V"].value_counts().head(10)

V
..    1272
Name: count, dtype: int64

In [ ]:
resp_meta = requests.get("https://servicodados.ibge.gov.br/api/v3/agregados/8880/metadados", headers={"User-Agent": "Mozilla/5.0"}, timeout=30)
meta = resp_meta.json()

# lista as classificações disponíveis (é aqui que deve estar o filtro que falta, tipo "receita nominal" vs "volume de vendas")
for c in meta.get("classificacoes", []):
    print(c["nome"], "-> id:", c["id"])
    for cat in c["categorias"]:
        print("   ", cat["id"], "-", cat["nome"])

Tipos de índice -> id: 11046
    56733 - Índice de receita nominal de vendas no comércio varejista
    56734 - Índice de volume de vendas no comércio varejista

In [ ]:
url_pmc = "https://apisidra.ibge.gov.br/values/t/8880/n3/50,51,52,53/v/7170/p/all/c11046/56734"
resp = requests.get(url_pmc, headers={"User-Agent": "Mozilla/5.0"}, timeout=60)
data = resp.json()

df_pmc_raw = pd.DataFrame(data[1:])
print(df_pmc_raw["V"].value_counts().head(5))
df_pmc_raw.head()

V
115.29873    1
36.27072     1
36.10235     1
36.39866     1
36.69372     1
Name: count, dtype: int64

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,3,Unidade da Federação,30,Número-índice,36.27072,50,Mato Grosso do Sul,7170,PMC - Número-índice com ajuste sazonal (2022=100),200001,janeiro 2000,56734,Índice de volume de vendas no comércio varejista
1,3,Unidade da Federação,30,Número-índice,36.10235,50,Mato Grosso do Sul,7170,PMC - Número-índice com ajuste sazonal (2022=100),200002,fevereiro 2000,56734,Índice de volume de vendas no comércio varejista
2,3,Unidade da Federação,30,Número-índice,36.39866,50,Mato Grosso do Sul,7170,PMC - Número-índice com ajuste sazonal (2022=100),200003,março 2000,56734,Índice de volume de vendas no comércio varejista
3,3,Unidade da Federação,30,Número-índice,36.69372,50,Mato Grosso do Sul,7170,PMC - Número-índice com ajuste sazonal (2022=100),200004,abril 2000,56734,Índice de volume de vendas no comércio varejista
4,3,Unidade da Federação,30,Número-índice,37.05593,50,Mato Grosso do Sul,7170,PMC - Número-índice com ajuste sazonal (2022=100),200005,maio 2000,56734,Índice de volume de vendas no comércio varejista

In [ ]:
df_pmc = df_pmc_raw.rename(columns={
    "D1C": "codigo_uf",
    "D1N": "uf",
    "D3C": "anomes",
    "V": "indice_volume_sazonal"
})[["codigo_uf", "uf", "anomes", "indice_volume_sazonal"]]

df_pmc = df_pmc[df_pmc["indice_volume_sazonal"] != ".."].copy()
df_pmc["indice_volume_sazonal"] = pd.to_numeric(df_pmc["indice_volume_sazonal"], errors="coerce")
df_pmc["anomes"] = df_pmc["anomes"].astype(int)

print("período:", df_pmc["anomes"].min(), "a", df_pmc["anomes"].max())
print(df_pmc.groupby("uf")["anomes"].count())

período: 200001 a 202606
uf
Distrito Federal      318
Goiás                 318
Mato Grosso           318
Mato Grosso do Sul    318
Name: anomes, dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.makedirs('/content/drive/MyDrive/projeto_varejo_centrooeste', exist_ok=True)

import sqlite3
conn = sqlite3.connect('/content/drive/MyDrive/projeto_varejo_centrooeste/varejo_co.db')

# salva o que já temos
df_pmc.to_sql("pmc_varejo", conn, if_exists="replace", index=False)
pd.read_sql("SELECT COUNT(*) FROM pmc_varejo", conn)

Mounted at /content/drive

   COUNT(*)
0      1272

In [ ]:
url_pib_teste = "https://apisidra.ibge.gov.br/values/t/5938/n6/in%20n3%2050,51,52,53/v/all/p/last"
resp = requests.get(url_pib_teste, headers={"User-Agent": "Mozilla/5.0"}, timeout=60)
data = resp.json()

df_pib_teste = pd.DataFrame(data[1:])
print(df_pib_teste.columns.tolist())
df_pib_teste[["D1N", "D2N", "V"]].head(10)

['NC', 'NN', 'MC', 'MN', 'V', 'D1C', 'D1N', 'D2C', 'D2N', 'D3C', 'D3N']

               D1N                                                D2N        V
0  Água Clara - MS           Produto Interno Bruto a preços correntes  1544633
1  Água Clara - MS  Participação do produto interno bruto a preços...     7.20
2  Água Clara - MS  Participação do produto interno bruto a preços...     3.40
3  Água Clara - MS  Participação do produto interno bruto a preços...     0.84
4  Água Clara - MS  Participação do produto interno bruto a preços...     0.13
5  Água Clara - MS  Participação do produto interno bruto a preços...     0.01
6  Água Clara - MS  Impostos, líquidos de subsídios, sobre produto...      ...
7  Água Clara - MS  Participação dos impostos, líquidos de subsídi...      ...
8  Água Clara - MS  Participação dos impostos, líquidos de subsídi...      ...
9  Água Clara - MS  Participação dos impostos, líquidos de subsídi...      ...

In [ ]:
print(df_pib_teste[["D2C", "D2N"]].drop_duplicates().to_string())

     D2C                                                                                                                                                                                                                                                                                                                            D2N
0     37                                                                                                                                                                                                                                                                                       Produto Interno Bruto a preços correntes
1    553                                                                                                                                                                                                Participação do produto interno bruto a preços correntes no produto interno bruto a preços correntes da microrregião geográfica
2    552                                                                                                                                                                                                 Participação do produto interno bruto a preços correntes no produto interno bruto a preços correntes da mesorregião geográfica
3    497                                                                                                                                                                                                   Participação do produto interno bruto a preços correntes no produto interno bruto a preços correntes da unidade da federação
4    530                                                                                                                                                                                                          Participação do produto interno bruto a preços correntes no produto interno bruto a preços correntes da grande região
5    496                                                                                                                                                                                                                 Participação do produto interno bruto a preços correntes no produto interno bruto a preços correntes do Brasil
6    543                                                                                                                                                                                                                                                             Impostos, líquidos de subsídios, sobre produtos a preços correntes
7    571                                                                                                                                          Participação dos impostos, líquidos de subsídios, sobre produtos a preços correntes nos impostos, líquidos de subsídios, sobre produtos a preços correntes da microrregião geográfica
8    570                                                                                                                                           Participação dos impostos, líquidos de subsídios, sobre produtos a preços correntes nos impostos, líquidos de subsídios, sobre produtos a preços correntes da mesorregião geográfica
9    545                                                                                                                                             Participação dos impostos, líquidos de subsídios, sobre produtos a preços correntes nos impostos, líquidos de subsídios, sobre produtos a preços correntes da unidade da federação
10   551                                                                                                                                                    Participação dos impostos, líquidos de subsídios, sobre produtos a preços correntes nos impostos, líquidos de subsídios, sobre produtos a preços correntes da grande região
11   544                                                                                                                                                           Participação dos impostos, líquidos de subsídios, sobre produtos a preços correntes nos impostos, líquidos de subsídios, sobre produtos a preços correntes do Brasil
12   498                                                                                                                                                                                                                                                                                Valor adicionado bruto a preços correntes total
13   555                                                                                                                                                                                  Participação do valor adicionado bruto a preços correntes total no valor adicionado bruto a preços correntes total da microrregião geográfica
14   554                                                                                                                                                                                   Participação do valor adicionado bruto a preços correntes total no valor adicionado bruto a preços correntes total da mesorregião geográfica
15   500                                                                                                                                                                                     Participação do valor adicionado bruto a preços correntes total no valor adicionado bruto a preços correntes total da unidade da federação
16   546                                                                                                                                                                                            Participação do valor adicionado bruto a preços correntes total no valor adicionado bruto a preços correntes total da grande região
17   499                                                                                                                                                                                                   Participação do valor adicionado bruto a preços correntes total no valor adicionado bruto a preços correntes total do Brasil
18   513                                                                                                                                                                                                                                                                      Valor adicionado bruto a preços correntes da agropecuária
19   516                                                                                                                                                                                                   Participação do valor adicionado bruto a preços correntes da agropecuária no valor adicionado bruto a preços correntes total
20   557                                                                                                                                                              Participação do valor adicionado bruto a preços correntes da agropecuária no valor adicionado bruto a preços correntes da agropecuária da microrregião geográfica
21   556                                                                                                                                                               Participação do valor adicionado bruto a preços correntes da agropecuária no valor adicionado bruto a preços correntes da agropecuária da mesorregião geográfica
22   515                                                                                                                                                                 Participação do valor adicionado bruto a preços correntes da agropecuária no valor adicionado bruto a preços correntes da agropecuária da unidade da federação
23   547                                                                                                                                                                        Participação do valor adicionado bruto a preços correntes da agropecuária no valor adicionado bruto a preços correntes da agropecuária da grande região
24   514                                                                                                                                                                               Participação do valor adicionado bruto a preços correntes da agropecuária no valor adicionado bruto a preços correntes da agropecuária do Brasil
25   517                                                                                                                                                                                                                                                                         Valor adicionado bruto a preços correntes da indústria
26   520                                                                                                                                                                                                      Participação do valor adicionado bruto a preços correntes da indústria no valor adicionado bruto a preços correntes total
27   559                                                                                                                                                                    Participação do valor adicionado bruto a preços correntes da indústria no valor adicionado bruto a preços correntes da indústria da microrregião geográfica
28   558                                                                                                                                                                     Participação do valor adicionado bruto a preços correntes da indústria no valor adicionado bruto a preços correntes da indústria da mesorregião geográfica
29   519                                                                                                                                                                       Participação do valor adicionado bruto a preços correntes da indústria no valor adicionado bruto a preços correntes da indústria da unidade da federação
30   548                                                                                                                                                                              Participação do valor adicionado bruto a preços correntes da indústria no valor adicionado bruto a preços correntes da indústria da grande região
31   518                                                                                                                                                                                     Participação do valor adicionado bruto a preços correntes da indústria no valor adicionado bruto a preços correntes da indústria do Brasil
32  6575                                                                                                                                                                                         Valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social
33  6574                                                                                                                     Participação do valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, no valor adicionado bruto a preços correntes total
34  6571  Participação do valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, no valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, da microrregião geográfica
35  6570   Participação do valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, no valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, da mesorregião geográfica
36  6572     Participação do valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, no valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, da unidade da federação
37  6569            Participação do valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, no valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, da grande região
38  6573                   Participação do valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, no valor adicionado bruto a preços correntes dos serviços, exclusive administração, defesa, educação e saúde públicas e seguridade social, do Brasil
39   525                                                                                                                                                                                                              Valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social
40   528                                                                                                                                           Participação do valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social no valor adicionado bruto a preços correntes total
41   563                                               Participação do valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social no valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social da microrregião geográfic
42   562                                               Participação do valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social no valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social da mesorregião geográfica
43   527                                                 Participação do valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social no valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social da unidade da federação
44   550                                                        Participação do valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social no valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social da grande região
45   526                                                               Participação do valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social no valor adicionado bruto a preços correntes da administração, defesa, educação e saúde públicas e seguridade social do Brasil

In [ ]:
url_pib = "https://apisidra.ibge.gov.br/values/t/5938/n6/in%20n3%2050,51,52,53/v/37/p/all"
resp = requests.get(url_pib, headers={"User-Agent": "Mozilla/5.0"}, timeout=60)
data = resp.json()

df_pib_raw = pd.DataFrame(data[1:])
df_pib = df_pib_raw.rename(columns={"D1C": "codigo_ibge_7d", "D3C": "ano", "V": "pib_mil_reais"})[
    ["codigo_ibge_7d", "ano", "pib_mil_reais"]
]

df_pib["codigo_ibge"] = df_pib["codigo_ibge_7d"].str[:-1]  # trunca pro formato de 6 dígitos, igual fizemos antes
df_pib["ano"] = df_pib["ano"].astype(int)
df_pib["pib_mil_reais"] = pd.to_numeric(df_pib["pib_mil_reais"], errors="coerce")

print("período:", df_pib["ano"].min(), "a", df_pib["ano"].max())
print("municípios distintos:", df_pib["codigo_ibge"].nunique())

período: 2002 a 2023
municípios distintos: 467

In [ ]:
url_pop = "https://apisidra.ibge.gov.br/values/t/6579/n6/in%20n3%2050,51,52,53/v/9324/p/all"
resp = requests.get(url_pop, headers={"User-Agent": "Mozilla/5.0"}, timeout=60)
data = resp.json()

df_pop_raw = pd.DataFrame(data[1:])
df_pop = df_pop_raw.rename(columns={"D1C": "codigo_ibge_7d", "D3C": "ano", "V": "populacao"})[
    ["codigo_ibge_7d", "ano", "populacao"]
]
df_pop["codigo_ibge"] = df_pop["codigo_ibge_7d"].str[:-1]
df_pop["ano"] = df_pop["ano"].astype(int)
df_pop["populacao"] = pd.to_numeric(df_pop["populacao"], errors="coerce")

print("período:", df_pop["ano"].min(), "a", df_pop["ano"].max())
print("municípios distintos:", df_pop["codigo_ibge"].nunique())

período: 2001 a 2025
municípios distintos: 468

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import sqlite3
import requests

conn = sqlite3.connect('/content/drive/MyDrive/projeto_varejo_centrooeste/varejo_co.db')

df_pmc = pd.read_sql("SELECT * FROM pmc_varejo", conn)
print(df_pmc.shape)

Mounted at /content/drive
(1272, 4)

In [ ]:
municipios_pib = set(df_pib["codigo_ibge"].unique())
municipios_pop = set(df_pop["codigo_ibge"].unique())

print("só na população, não no PIB:", municipios_pop - municipios_pib)
print("só no PIB, não na população:", municipios_pib - municipios_pop)

só na população, não no PIB: {'510183'}
só no PIB, não na população: set()

In [ ]:
df_pop_raw[df_pop_raw["D1C"].str[:-1] == "510183"][["D1C", "D1N"]].drop_duplicates()

          D1C                          D1N
2016  5101837  Boa Esperança do Norte - MT

In [ ]:
df_pop = df_pop[df_pop["codigo_ibge"] != "510183"].copy()
print(df_pop["codigo_ibge"].nunique())  # deve dar 467 agora, batendo com o PIB

467

In [ ]:
df_pib_per_capita = df_pib.merge(df_pop, on=["codigo_ibge", "ano"], how="inner")

# PIB vem em MIL reais -- multiplica por 1000 antes de dividir pela população
df_pib_per_capita["pib_per_capita"] = (df_pib_per_capita["pib_mil_reais"] * 1000) / df_pib_per_capita["populacao"]

print(df_pib_per_capita.shape)
df_pib_per_capita[df_pib_per_capita["codigo_ibge"] == "520870"][["ano", "pib_per_capita"]]  # confere Goiânia como sanity check

(8406, 7)

       ano  pib_per_capita
5652  2002     9790.036785
5653  2003    10736.213753
5654  2004    11973.772640
5655  2005    12880.146311
5656  2006    14920.173679
5657  2008    17671.138802
5658  2009    19618.572905
5659  2011    25172.923547
5660  2012    28090.088449
5661  2013    28834.224208
5662  2014    32718.003291
5663  2015    32593.338072
5664  2016    32176.899145
5665  2017    33455.433274
5666  2018    32992.871589
5667  2019    34943.349869
5668  2020    33741.766308
5669  2021    38486.435043

In [ ]:
# pega o PIB per capita do ano mais recente disponível por município
df_pib_recente = df_pib_per_capita.sort_values("ano").groupby("codigo_ibge").tail(1)[
    ["codigo_ibge", "ano", "pib_per_capita"]
].rename(columns={"ano": "ano_pib"})

print(df_pib_recente["ano_pib"].value_counts())
df_pib_recente.head()

ano_pib
2021    467
Name: count, dtype: int64

     codigo_ibge  ano_pib  pib_per_capita
53        500060     2021    50530.350088
71        500070     2021    24072.979160
8369      522220     2021    27890.869633
35        500025     2021    43341.956641
4445      520250     2021    28238.394584

In [ ]:
ultimo_mes = df_pmc_recente["anomes"].max()

# .unique() antes do sort -- sem isso, cada mês repetido (1x por UF) distorce a contagem posicional
meses_unicos = sorted(df_pmc_recente[df_pmc_recente["anomes"] < ultimo_mes]["anomes"].unique())
mes_12m_atras = meses_unicos[-12]

print("mês mais recente:", ultimo_mes, "| referência 12m atrás (corrigido):", mes_12m_atras)

df_tendencia = df_pmc_recente[df_pmc_recente["anomes"].isin([ultimo_mes, mes_12m_atras])].pivot(
    index="uf", columns="anomes", values="indice_volume_sazonal"
)
df_tendencia.columns = ["indice_12m_atras", "indice_atual"]
df_tendencia["variacao_12m_pct"] = (df_tendencia["indice_atual"] / df_tendencia["indice_12m_atras"] - 1) * 100

df_tendencia.reset_index()

mês mais recente: 202606 | referência 12m atrás (corrigido): 202506

                   uf  indice_12m_atras  indice_atual  variacao_12m_pct
0    Distrito Federal         106.98401     115.29873          7.771928
1               Goiás         106.43238     106.26607         -0.156259
2         Mato Grosso         110.32145     108.99928         -1.198470
3  Mato Grosso do Sul         107.95932     110.55647          2.405675

In [ ]:
df_municipios = df_pib_recente.merge(
    df_pop[df_pop["ano"] == df_pop["ano"].max()][["codigo_ibge", "populacao"]],
    on="codigo_ibge", how="left"
)

# traz a UF de cada município a partir do próprio código (os 2 primeiros dígitos do código de 6 já indicam a UF)
mapa_uf = {"50": "Mato Grosso do Sul", "51": "Mato Grosso", "52": "Goiás", "53": "Distrito Federal"}
df_municipios["uf"] = df_municipios["codigo_ibge"].str[:2].map(mapa_uf)

df_municipios = df_municipios.merge(df_tendencia.reset_index()[["uf", "variacao_12m_pct"]], on="uf", how="left")

print(df_municipios.shape)
df_municipios.isnull().sum()

(467, 6)

codigo_ibge         0
ano_pib             0
pib_per_capita      0
populacao           0
uf                  0
variacao_12m_pct    0
dtype: int64

In [ ]:
df_municipios["tercil_renda"] = pd.qcut(df_municipios["pib_per_capita"], 3, labels=["baixa", "média", "alta"])
df_municipios["tercil_populacao"] = pd.qcut(df_municipios["populacao"], 3, labels=["baixa", "média", "alta"])

def classificar_formato(row):
    renda = row["tercil_renda"]
    pop = row["tercil_populacao"]

    if renda == "baixa" and pop == "baixa":
        return "Risco (sem escala nem renda)"
    elif renda == "baixa" and pop in ["média", "alta"]:
        return "Atacarejo"
    elif renda == "alta" and pop in ["média", "alta"]:
        return "Varejo tradicional"
    elif renda == "alta" and pop == "baixa":
        return "Varejo de nicho (renda alta, população pequena)"
    else:  # renda média
        return "Misto / avaliar caso a caso"

df_municipios["perfil_formato"] = df_municipios.apply(classificar_formato, axis=1)

print(df_municipios["perfil_formato"].value_counts())
df_municipios.groupby("perfil_formato")[["pib_per_capita", "populacao"]].mean()

perfil_formato
Misto / avaliar caso a caso                        155
Varejo tradicional                                 119
Atacarejo                                           87
Risco (sem escala nem renda)                        69
Varejo de nicho (renda alta, população pequena)     37
Name: count, dtype: int64

                                                 pib_per_capita     populacao
perfil_formato
Atacarejo                                          21069.049127  38189.735632
Misto / avaliar caso a caso                        38742.928600  43559.077419
Risco (sem escala nem renda)                       22650.486784   3542.971014
Varejo de nicho (renda alta, população pequena)   111492.499959   3744.945946
Varejo tradicional                                 99885.966080  56939.067227

In [ ]:
df_municipios.to_csv('/content/drive/MyDrive/projeto_varejo_centrooeste/municipios_formato.csv', index=False, encoding='utf-8-sig')
print("salvo")

salvo

In [ ]:
df_municipios.to_sql("municipios_formato_varejo", conn, if_exists="replace", index=False)

467

In [1]:
from google.colab import userdata
import subprocess

GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
GITHUB_USER = "renatofb98"
REPO_NAME = "Data_science_projects"
PASTA_PROJETO = "varejo-centrooeste"  # pasta dentro do repo pra esse projeto

repo_url = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{REPO_NAME}.git"

In [2]:
!git clone {repo_url} /content/repo
%cd /content/repo
!git config user.email "renato2014fernandes@gmail.com"
!git config user.name "Renato Borges Fernandes"

Cloning into '/content/repo'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 45 (delta 12), reused 9 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (45/45), 136.61 KiB | 4.27 MiB/s, done.
Resolving deltas: 100% (12/12), done.
/content/repo

In [3]:
import shutil, os

def publicar_no_github(mensagem_commit):
    pasta_destino = f"/content/repo/{PASTA_PROJETO}"
    os.makedirs(pasta_destino, exist_ok=True)

    # copia os arquivos relevantes do Drive pro repo local
    origem = "/content/drive/MyDrive/projeto_varejo_centrooeste"
    for arquivo in os.listdir(origem):
        if arquivo.endswith((".csv", ".md", ".ipynb", ".pbix")):
            shutil.copy(os.path.join(origem, arquivo), pasta_destino)

    %cd /content/repo
    !git add {PASTA_PROJETO}
    !git commit -m "{mensagem_commit}"
    !git push
    print("Publicado no GitHub.")

In [5]:
from google.colab import drive
import os

# Ensure Google Drive is mounted
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# Ensure the project directory exists
project_path = '/content/drive/MyDrive/projeto_varejo_centrooeste'
if not os.path.exists(project_path):
    os.makedirs(project_path, exist_ok=True)
    print(f"Directory {project_path} was created.")
else:
    print(f"Directory {project_path} already exists.")

publicar_no_github("Atualiza dashboard de adequação de formato varejo")

Mounted at /content/drive
Directory /content/drive/MyDrive/projeto_varejo_centrooeste already exists.
/content/repo
[main 4f4166c] Atualiza dashboard de adequação de formato varejo
 1 file changed, 468 insertions(+)
 create mode 100644 varejo-centrooeste/municipios_formato.csv
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 9.92 KiB | 4.96 MiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/renatofb98/Data_science_projects.git
   cb96ffe..4f4166c  main -> main
Publicado no GitHub.